dist: xenial  
language: python
python:
  - "3.7"
install:
  - pip install git+https://rshanker779@github.com/rshanker779/rshanker779_common.git#egg=rshanker779_common
  - python setup.py install
script:
  - black --check .
  - python setup.py test